# Generated by Django 3.2.3 on 2021-06-03 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0006_alter_customunit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Categorization field (e.g.: customer ID)')),
                ('unit_system', models.CharField(choices=[('Planck', 'Planck'), ('SI', 'SI'), ('US', 'US'), ('atomic', 'atomic'), ('cgs', 'CGS'), ('imperial', 'imperial'), ('mks', 'mks')], max_length=20, verbose_name='Unit system to register the unit in')),
                ('code', models.SlugField(verbose_name='technical name of the dimension (e.g.: myDimension)')),
                ('name', models.CharField(max_length=255, verbose_name='Human readable name (e.g.: My dimension)')),
                ('relation', models.CharField(max_length=255, verbose_name='Relation to existing dimensions (e.g.: [mass]*[length]/[time])')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimensions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
