# Generated by Django 3.2.3 on 2021-06-03 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0007_customdimension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdimension',
            options={'ordering': ['name', 'code']},
        ),
        migrations.AlterField(
            model_name='customdimension',
            name='code',
            field=models.CharField(max_length=255, verbose_name='technical name of the dimension (e.g.: [myDimension])'),
        ),
        migrations.AlterUniqueTogether(
            name='customdimension',
            unique_together={('user', 'key', 'code')},
        ),
    ]
