# Generated by Django 3.2 on 2021-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_auto_20210419_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
